name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit count
        id: get_version
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "version=$COMMIT_COUNT" >> $GITHUB_OUTPUT

      - name: Create info.json
        run: |
          echo "{\"version\": ${{ steps.get_version.outputs.version }}}" > info.json

      - name: Create ZIP archive
        run: zip -r app.zip . -x "*.git*"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}